package com.escrowflow.domain.enums;

public enum NotificationType {
    PROJECT_CREATED,
    WORK_SUBMITTED,
    DISPUTE_RAISED,
    DISPUTE_RESOLVED,
    REVIEW_RECEIVED,
    APPLICATION_RECEIVED,
    APPLICATION_ACCEPTED,
    APPLICATION_DECLINED
}
